### PR TITLE
Update who's using MobX list

### LINKED ISSUE #8: Re-sync who-uses MobX list
See: https://github.com/mobxjs/mobx/issues/681

### PR DESCRIPTION
**Pull request by hawkins**
Fixes #8 

cc @mweststrate 

---

Still todo:

- [ ] Add images to `README-CN.md`?
- [x] Decide whether or not we should port `USERS.md` to Chinese. (cc @SangKa )

### CODE REVIEW

**Comment by hawkins** [comment]
I'm not convinced the users doc is worth translating yet, since that will probably be a frequent update and infrequent reference. Since the information in the later entries is so informal anyways, it seems like there isn't quite enough value in it to maintain the document across multiple languages; maybe just rely on Google Translate or similar for that? Thoughts, @SangKa ?

That being said I think it'd be good to add the same "Who's using MobX" logo block to the CN doc, but link to `USERS.md`. I can do that part, of course.

**Comment by SangKa** [comment]
Got it, I will follow up.
`README.md`  will navigate to the `USERS.md` as normal.
`README-CN.md` will navigate to the `USERS-CN.md` which is a translation version of `USERS.md`.

**Comment by hawkins** [comment]
I'm worried that would lead to more frequent work than you'd like, but since you're cool with it for now, that sounds great. Thanks! 👍

**Comment by SangKa** [comment]
I'm cool ~

**Pull request merged**
