### PR TITLE
add Introduction to MobX 4 for React/Redux Developers

### PR DESCRIPTION
**Pull request by tsiq-swyx**
add Introduction to MobX 4 for React/Redux Developers

### CODE REVIEW

**Comment by hawkins** [comment]
Hey, thanks for this!

We'll need to translate this to Chinese before merging. Also, I haven't checked if it's a duplicate or not but it looks like not. I'm going to hold off on merging this for now since I'm working on a bot to automate tasks like translation, duplicate checking, etc. 😄

If you'd rather we merge it asap, I'll be happy to merge if you also update `README-CN.md` with a translation, but no worries if not, since the bot will handle this soon 👍

**Comment by tsiq-swyx** [comment]
haha its not because I wrote it :) why exactly is the chinese translation important? i'm new to this repo so i dont know whats going on. anyway, im happy to let the process run its course. cheers.

**Comment by hawkins** [comment]
I didn't notice that, whoops! Looks great! 👏 

We've got a bunch of Chinese users actually, so since translation is mostly trivial, it's good to keep them in sync. Just plug-and-chug to Google Translate is generally enough, I think.

**Comment by tsiq-swyx** [comment]
umm as a basic chinese speaker that is most probably going to be extremely
useless lol. google translate isn't that good.

**Comment by hawkins** [comment]
I was worried about this, but it looks like translations are done on a best-effort case so technical translations have lots of "english" words like "MobX" in them. So I'm not sure how great they really are, since I don't read or speak the language personally.

Would you mind taking a quick glance at our `README-CN.md` file when you get 2-3 minutes then, please? I'd love to hear your thoughts on its value as a chinese speaker 🙌

**Comment by tsiq-swyx** [comment]
mm is this all autotranslated? its got a lot of pretty good idioms eg 入门
<https://mobx.js.org/getting-started.html> for Introductions. thats pretty
nice but also on the easier side for autotranslation. i think where it runs
into trouble is longer form writing like with actual article content,
instead of simple one-sentence descriptions. I think all of README-CN.md is
completely fine and readable.

unsolicited opinion incoming:

personally what im more concerned about is staleness of info. awesome-
lists progressively lose awesomeness as they age. you should WANT to
consign things to the history bin. I've told mwestrate that his egghead.io
course is way outdated now and he agrees. imo we shouldnt have anything
>2yrs old on the list. frankly even >1yr is a stretch. the space just
evolves way too quickly to keep shit on there. if something is important
and getting old, call for new content to be made to replace it.

**Comment by hawkins** [comment]
Only parts of it are auto translated, most of it is per the gracious help of @SangKa :) 

> unsolicited opinion ...

I completely agree, the bot will also help us trim the fat by checking how old resources are when possible (github repos, medium posts, youtube vids etc). That's something we've sorely been lacking in order to get our list listed as an official awesome list at this time.

Thanks for your feedback!!

**Comment by tsiq-swyx** [comment]
well thank you for maintaining it :)

**Pull request merged**
